name: 'Check Dependabot Alerts with Break the Build'
description: 'Check for open dependabot alerts and validate against thresholds.'
author: 'Lucas Ventura'
inputs:
  github_token:
    description: The GitHub token used to create an authenticated client. It needs to be a PAT token with the `dependabot` read scope.
    default: ${{ github.token }}
    required: false
  owner:
    description: The owner of the repository
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: The name of the repository
    default: ${{ github.event.repository.name }}
    required: false
  max_high_alerts:
    description: 'Maximum allowed high severity alerts'
    required: false
  max_critical_alerts:
    description: 'Maximum allowed critical severity alerts'
    required: false
  max_medium_alerts:
    description: 'Maximum allowed medium severity alerts'
    required: false
  max_low_alerts:
    description: 'Maximum allowed low severity alerts'
    required: false
  do_not_break_pr_check:
    description: 'Do not break the PR check if the thresholds are exceeded'
    required: false
    default: false
    type: boolean
  
outputs:
  total_alerts:
    description: 'Total number of alerts'
  critical_alerts:
    description: 'Number of critical severity alerts'
  high_alerts:
    description: 'Number of high severity alerts'
  medium_alerts:
    description: 'Number of medium severity alerts'
  low_alerts:
    description: 'Number of low severity alerts'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'shield'
  color: 'red'
